### ISSUE TITLE
Update metadata for a video

### ISSUE THREAD

**Issue by IonicaBizau** [phillipj/node-plex-api#59] opened 2016-03-14 10:57 UTC
How can I update the metadata for a specific video?

Thanks! :sparkle:

**Comment by phillipj** [comment] 2016-03-23 20:15
@IonicaBizau I haven't seen many URLs in the API which supports altering data. You might get more replies opening an issue in either https://github.com/drzoidberg33/plexpy or https://github.com/plexinc/plex-media-player

**Comment by IonicaBizau** [comment] 2016-03-23 20:20
@phillipj Actually, it was pretty easy: just changing the `POST` into `PUT`. I'm changing it right now and submit a PR.

**Comment by phillipj** [comment] 2016-03-24 07:57
Awesome! Did you find PUTs documented somewhere?

**Comment by IonicaBizau** [comment] 2016-03-24 08:02
@phillipj Basically they use PUT requests to update the resources (it did not work with POST). I saw it in the browser developer tools. I opened #61 and I added there an example.

**Comment by phillipj** [comment] 2016-03-24 16:50
Thanks for investigating this and contributing :+1:

**Comment by balaram123** [comment] 2016-04-02 09:43
How can i Integrate this plex server to the visual studio windows application

**Comment by phillipj** [comment] 2016-04-02 20:01
Closing this issue as it you found the answer to updating metadata youself

**Closed by phillipj** 2016-04-02 20:01 UTC
Labels: question

**Comment by phillipj** [comment] 2016-04-02 20:06
@balaram123 please open a new issue with your question. Include more info about you are doing and your setup, as it's needed for us to help you further.

**Comment by laurentchicoine** [comment] 2016-08-23 02:01
@phillipj I wasn't able to make the putQuery function work in the way it was presented in the doc. The function was just not calling back anything. I ended up finding that I needed to add a type=1 parameter to make it work.

client.putQuery("/library/sections/3/all?**type=1&**id=123&summary.value=updatedSummaryText")
    .then(function (result) {
        console.log("Description of video by id 123 has been set to 'updatedSummaryText'");
    }, function (err) {
        throw new Error("Could not connect to server");
    });

I'm not sure if this is caused by me Plex server version or maybe the type of video library I use. Anyway, I just wanted to post this here so it can help others. Also if you find that type=1 should be included, maybe you could update the doc.

**Comment by phillipj** [comment] 2016-08-24 07:08
Huh that's strange!

Do you know what type=1 means to the Plex Server? Where did you find hints
about that being needed? What version of Plex Server are you using?

Thanks for reaching out about this 👍

**Comment by laurentchicoine** [comment] 2016-08-25 00:19
I don't know what it means to the Plex Server.

I found the type=1 parameter when exploring the Network tab of the Google Chrome Developer Tools. When you manually update a metadata from a content, the web interface is using the Plex API. So I inspected the PUT that was called and found out it was including the parameter type=1.

As for the version, I tried this on two different versions, a Windows version 1.0.3.2461 and a Ubuntu version running version 0.9.12.18

**Comment by phillipj** [comment] 2016-10-16 19:35
@laurentchicoine way overdue, but I just updated the `.putQuery()` example with commit https://github.com/phillipj/node-plex-api/commit/d9d67e48e6b032f553048f20c99fe18ed523257e , after reproducing the same behaviour on my server.

Thanks so much for reporting this! 👍
