### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by DrEVILish** [phillipj/node-plex-api#102] opened 2019-05-30 12:57 UTC
I've copied the example filled out the relevant information and it keeps giving me back this error when I try and connect to the API.

Not sure what I'm missing.

```
(node:27317) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not connect to server
(node:27317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
const PlexAPI = require('plex-api');
const client = new PlexAPI({
    hostname: '192.168.1.xx',
    https: true,
    username: 'myPlexUsername',
    password: 'superSecretPassword',
    managedUser: {
        name: 'myPlexUsername',
        pin: '1234'
    }
});
```

**Comment by wwwizzarrdry** [comment] 2019-06-08 05:57
I have no issues using the following.  Please note the use of the plex.direct uri for `hostname` when you have enabled `https`. Perhaps that is your issue? I know that was my problem. I didn't even know about the plex.direct uri...

If it's not an issue with the https option, then my guess is that things have changed in the case of authenticating managed users.


**Note:** the `*`'d props are based on the config you provided. I don't use them in my case.
```
const clearText = false;
const client = new PlexAPI({
    hostname: (clearText) ? "192.168.2.100" : "192-168-2-100.####.plex.direct",  
    port: 32400,
    https: clearText,
    token: "xY6781FEJUix3qvndr5", // acquired via Plex Pin module
    timeout: 6000,
    *username: "un",
    *password: "pw",
    *managedUser: {
        name: 'mun',
        pin: 'mpw'
    },
    options: {
        identifier: "a46616f7-3d3e-42d2-b78d-5c2dfb6c6fb6", 
        product: "Node App",
        version: "1.0",
        deviceName: "Node.js",
        platform: "Node.js",
        platformVersion: "v8.11.3"
    }
});
```

**Comment by wwwizzarrdry** [comment] 2019-06-08 06:01
I also don't know how to obtain the plex direct uri, which i need to figure out. I currently just open devtools on an authenticated session in the browser and copy the uri from there. This whole process is pointless if I can't automate this part of the auth.

**Comment by phillipj** [comment] 2019-06-08 12:41
To ensure I've got this right before dive into what might be causing this; you got those unhandled promise warnings directly after creating an client with `new PlexAPI(..)` or are you invoking other functions first, like `client.query(..)` or similar?

**Comment by wwwizzarrdry** [comment] 2019-06-08 16:08
I spun up a test today and confirmed that you need to use the plex.direct uri when you enable https.

Beyond that, I don't have Plex Home enabled, so I didn't test anything else. My guess is that when @DrEVILish replaces his hostname with the correct plex.dorect uri, everything else will work fine.


Anyone know how to get a Plex.direct certificate hash programmatically?

**Comment by phillipj** [comment] 2020-10-28 18:27
Closing this since the author didn't end up answering our questions.

**Closed by phillipj** 2020-10-28 18:27 UTC
